added initial support to build rocm

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -308,6 +308,7 @@ if is_windows; then
   TF_NEED_JEMALLOC=0
   TF_NEED_OPENCL=0
   TF_CUDA_CLANG=0
+  TF_NEED_ROCM=0
 fi
 
 if is_linux; then
@@ -800,7 +801,6 @@ done
 # end of if "$TF_NEED_OPENCL" == "1"
 fi
 
-
 while [ "$TF_NEED_MPI" == "" ]; do
   read -p "Do you wish to build TensorFlow with "\
 "MPI support? [y/N] " INPUT
@@ -877,5 +877,54 @@ if [ "$TF_NEED_MPI" == "1" ]; then
   fi
 fi
 
+
+# Check for ROCM
+
+if is_linux; then
+if [[ "$TF_ENABLE_XLA" == "1" ]]; then
+while [ "$TF_NEED_ROCM" == "" ]; do
+  read -p "Do you wish to build TensorFlow with ROCM support? [y/N] " INPUT
+  case $INPUT in
+    [Yy]* ) echo "ROCM support will be enabled for TensorFlow"; TF_NEED_ROCM=1;;
+    [Nn]* ) echo "No ROCM support will be enabled for TensorFlow"; TF_NEED_ROCM=0;;
+    "" ) echo "No ROCM support will be enabled for TensorFlow"; TF_NEED_ROCM=0;;
+    * ) echo "Invalid selection: " $INPUT;;
+  esac
+done
+if [[ "$TF_NEED_ROCM" == "1" ]]; then
+  echo "HCC will be used as ROCM compiler"; TF_ROCM_HCC=1;
+fi
+fi
+fi
+
+export TF_NEED_ROCM
+write_action_env_to_bazelrc "TF_NEED_ROCM" "$TF_NEED_ROCM"
+
+export TF_ROCM_HCC
+write_action_env_to_bazelrc "TF_ROCM_HCC" "$TF_ROCM_HCC"
+
+# Check whether HCC is available with ROCM enabled
+while [[ "$TF_ROCM_HCC" == "1" ]] && true; do
+  fromuser=""
+  if [ -z "$HCC_ROCM_COMPILER_PATH" ]; then
+    default_hcc_host_compiler_path=$(which hcc || true)
+    read -p "Please specify which hcc should be used as device and host compiler. [Default is $default_hcc_host_compiler_path]: " HCC_ROCM_COMPILER_PATH
+    fromuser="1"
+    if [ -z "$HCC_ROCM_COMPILER_PATH" ]; then
+      HCC_ROCM_COMPILER_PATH="$default_hcc_host_compiler_path"
+    fi
+  fi
+  if [ -e "$HCC_ROCM_COMPILER_PATH" ]; then
+    export HCC_ROCM_COMPILER_PATH
+    write_action_env_to_bazelrc "HCC_ROCM_COMPILER_PATH" "$HCC_ROCM_COMPILER_PATH"
+    break
+  fi
+  echo "Invalid hcc path. ${HCC_ROCM_COMPILER_PATH} cannot be found" 1>&2
+  if [ -z "$fromuser" ]; then
+    exit 1
+  fi
+  HCC_ROCM_COMPILER_PATH=""
+  # Retry
+done
 
 echo "Configuration finished"
